### ISSUE TITLE
tutorials are not appearing on the website

### ISSUE THREAD

**Issue by aaronmarkham** [mli/deepnumpy-doc#12]
Only three out of six tutorials are showing up in the crash course:
http://numpy.mxnet.io/guide/crash-course/index.html

**Comment by reminisce** [comment]
It's probably because we skipped running GPU-related notebooks in the CI since the nightly build pipeline always times out for making GPU wheels. There is also a binary size limit issue to resolve with pypi support, which has been filed here: https://github.com/pypa/pypi-support/issues/50.

If you just need html files to upload to mxnet website, I may be able to provide those by building the docs locally.

**Comment by aaronmarkham** [comment]
> It's probably because we skipped running GPU-related notebooks in the CI since the nightly build pipeline always times out for making GPU wheels. There is also a binary size limit issue to resolve with pypi support, which has been filed here: [pypa/pypi-support#50](https://github.com/pypa/pypi-support/issues/50).
> 
> If you just need html files to upload to mxnet website, I may be able to provide those by building the docs locally.

AFAIK, it's a different host and deploy process than mxnet.io. Meaning that I'm pretty sure it isn't there, but I don't know where it is.

**Comment by reminisce** [comment]
All notebooks are back online again. Closing this.
